# scheam.yml

version: 2

sources:
    - name: raw #reneommer le nom du data-set
      schema: gz_raw_data #où se situe le dataset
      description: source de données brutes greenweez
      tables:

        - name: sales
          identifier: raw_gz_sales #nom exact de la table dans BQ
          description: sales of greenweez / nous avons un ligne par product_id pour chaque order_id

          #Freshness testing - make sure to fill in the 
          loaded_at_field: "CAST(date_date AS TIMESTAMP)" #AS date_date
          freshness: 
            warn_after: {count: 90, period: day} #Erreur si plus de 90 jours

          columns:
            - name: date_date
              description: date of purchase
            - name: orders_id
              description: id de chaque order acheté
            - name: pdt_id
              description: id de chaque produit acheté
            - name: revenue
              description: revenue de chaque produit/order acheté
            - name: quantity
              description: quantité achetée
            - name: "(orders_id || '-' || pdt_id)"
              description: primary key of the table
              tests:
                - unique
                - not_null
        - name: product
          identifier: raw_gz_product
          description: products of greenweez / purchase price by products_id
          columns:
            - name: products_id
              description: primary key of the table
              tests:
                - unique
                - not_null 
            - name: purchSE_PRICE
              description: prix unitaire pour chaque produit
        - name: ship
          identifier: raw_gz_ship
          description: ship fee and cost by orders_id (pk)
          columns:
            - name: orders_id
              description: primary key of the table
              tests:
                - unique
                - not_null
            - name: shipping_fee
              description: frais de transport payé par les clients
            - name: shipping_fee_1
              description: duplicatat de shipping fee 
            - name: logCost
              description: coût logistique de chaque order
            - name: ship_cost
              description: prix de transport pour chaque order

models:
  - name: int_sales_margin
    description: marges par order et produit
    columns:
      - name: products_id
        description: id de chaque produit vendue
      - name: date_date
        description: date de vente du produit
      - name: orders_id
        description: id de chaque order
      - name: revenue
        description: revenue de chaque order
      - name: quantity
        description: quantité de chaque order
      - name: purchase_price
        description: prix de chaque produit
      - name: purchase_cost
        description: prix de chaque order
      - name: margin
        description: marge de chaque produit
      - name: "(orders_id || '-' || products_id)"
        description: primary key of the table
        tests:
          - unique
          - not_null
  - name: int_orders_margin
    description: marge par order
    columns:
      - name: orders_id 
        description: id de chaque order (pk)
        tests:
          - unique
          - not_null
      - name: date_date
        description: date de chaque order
        tests:
          - not_null
      - name: revenue
        description: revenue de chaque order
        tests:
          - not_null
      - name: quantity
        description: quantité de produits par order
        tests:
          - not_null
      - name: purchase_cost
        description: prix d'achat pour chaque order
        tests:
          - not_null
      - name: margin
        description: marge par order
        tests:
          - not_null

  #Marge Operationnel
  - name: int_orders_operational
    description: marge opérationnelle par order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: date_date
        description: date de chaque order
        tests:
          - not_null
      - name: revenue
        description: total revenue par order
        tests:
          - not_null
      - name: margin
        description: marge par order
        tests:
          - not_null
      - name: operational_margin
        description: marge opérationnel par order
        tests:
          - not_null
      - name: purchase_cost
        description: prix d'achat par order
        tests:
          - not_null
      - name: shipping_fee
        description: frais de transport par order
        tests:
          - not_null
      - name: log_cost
        description: frais de logistique par order
        tests:
          - not_null
      - name: quantity
        description: quantité total vendue par order
        tests:
          - not_null
  #Financial days report
  - name: finance_days
    description: mart model pour la finance
    columns:
      - name: date_date
        description: primary key 
        tests:
          - unique
          - not_null
      - name: nb_transactions
        description: nombre de transaction par jour
        tests:
          - not_null
      - name: revenue
        description: revenue total par jour
        tests:
          - not_null
      - name: average_basket
        description: panier moyen par jour
        tests:
          - not_null
      - name: margin
        description: marge total par jour
        tests:
          - not_null
      - name: operational_margin
        description: marge opérationnel par jour
        tests:
          - not_null
      - name: total_purchase_cost
        description: coût total par jour
        tests:
          - not_null
      - name: total_shipping_fee
        description: frais de transport par jour
        tests:
          - not_null
      - name: total_log_cost
        description: frais de logistique par jour
        tests:
          - not_null
      - name: total_pdt_sold
        description: nombre total de produits venus par jour
        tests:
          - not_null
        